apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environments
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: brandonphillips
        repo: gitopscon-testing
        labels:
        - preview
      requeueAfterSeconds: 5
  template:      
    metadata:
      name: 'simple-deployment-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: https://github.com/brandonphillips/gitopscon-testing.git
        targetRevision: '{{head_sha}}'
        path: base
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'simple-deployment-{{branch}}-{{number}}'
      
      
