---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  annotations:
    codefresh.io/app: simple-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        imagePullPolicy: Always
        image: fleatbnp/webserver-simple:5ce07a9ebe90a28a7e1f4e521f6e879dc7133a3a
        ports:
        - containerPort: 8080        


