replicaCount: 1
name: trivial-go-web-app
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: '6109cba35fec2e2f492985ebfc2a6cf437e437c6'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 8080
  portName: http
