replicaCount: 1
name: trivial-go-web-app
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: '500e873178963dadd75b71b0c79563a71fba7dc0'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 8080
  portName: http
