replicaCount: 1
name: trivial-go-web-app
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: '580cd07062c2a7caf9f6d3e58853b92efc778ad4'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 8080
  portName: http
