replicaCount: 1

name: trivial-go-web-app
env: staging
namespace: staging

image:
  name: webserver-simple
  tag: 'aae4524acce1133de842528c6328733afcd9d1ec'
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8418
  targetPort: 8080
  portName: http