replicaCount: 1

name: trivial-go-web-app
env: staging
namespace: staging

image:
  name: webserver-simple
  tag: ''
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  portName: http