replicaCount: 1
name: trivial-go-web-app
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: 'c3b06d11df9338251f0355a9fef4e7d6073b296c'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 8080
  portName: http
